@startuml 03-secuencia-FCFS
title Secuencia FCFS (sandbox sin costos)

autonumber
actor "FuenteArribos" as Arr
participant "Engine" as Eng
participant "Scheduler\n(FCFS)" as Sch
participant "ReadyQueue\n(FIFO)" as RQ
participant "CPU" as CPU
participant "Proceso" as P

== Arribo ==
Arr -> Eng: nuevoProceso(pid, burst)
Eng -> RQ: onArribo(pid)  # encola al final (FIFO)
note right of RQ
  FCFS: la PCB entra por el tail.
  El cabeza de la cola tiene prioridad.
end note

== Despacho mínimo ==
Eng -> CPU: isIdle?
CPU --> Eng: true
Eng -> Sch: elegirSiguiente()
Sch -> RQ: popHead()
RQ --> Sch: pid
Sch --> Eng: pid

Eng -> CPU: dispatch(pid)  ## L→C
note over CPU
  El dispatcher asigna CPU
  (no expropiativo en FCFS).
end note

== Ejecución de ráfaga ==
CPU -> P: startBurst(pid)
... ejecutando ráfaga en CPU ...
P --> CPU: endBurst(pid)

== Terminación ==
CPU -> Eng: notificarFin(pid)
Eng -> Eng: emitirEvento C→T
Eng -> P: finalizar(pid)

@enduml
